from Client import SendData
lista=[]
lista.append("djbokoboko")
lista.append("Imola")
lista.append("Z4 E89 35is")
lista.append("60001")
lista.append("195.4")
lista.append("30151")
lista.append("20000")
lista.append("0")
lista.append("Off")
lista.append("Off")
lista.append("Off")
lista.append("Off")
lista.append("Off")
lista.append("Off")
lista.append("Off")
lista.append("Off")
lista.append("Off")
lista.append("Off")
lista.append("1")
lista.append("1")
lista.append("Greece")
lista.append("Wheel")
lista.append("Hotlap")
lista.append("s1")
SendData(lista)